### ISSUE TITLE
Can staticdhcpd make a lease table from watching DHCP traffic?

### ISSUE THREAD

**Issue by ghost** [flan/staticdhcpd#77]
I need a leases table that is as up to date as possible for my local network.

I do not however have any access the the DHCP server on the network to get its leases table.

I’m wondering if there is a way to configure staticdhcpd so that it records all broadcast dhcp traffic that it sees, and updates it leases table.

That way I will have a local copy of the leases table that has been built up by watching DHCP traffic.

Is that possible with staticdhcpd? If yes, how?  If not, can anyone suggest a lightweight alternative way to do that without resorting to something heavyweight like networking monitoring with wireshark?

thanks

**Comment by flan** [comment]
You could use the hook described at http://static.uguu.ca/projects/staticDHCPd/doc/customisation/scripting.html#handleunknownmac to record details if the method matches what you're interested in (probably OFFERs) and just return None to have the server do nothing.

I need to fix the formatting on that element, though. The last two entries are rendering as plain text at the end.

But, if you need something lighter, you can use the underlying library without the full DHCPd logic on top: http://static.uguu.ca/projects/libpydhcpserver/doc/api/index.html#api-all-you-need-to-know

Create an instance of the server and implement the handle-functions you care about and that should be enough.

**Comment by flan** [comment]
https://github.com/flan/staticdhcpd/blob/2.0.x/staticDHCPd/staticdhcpdlib/dhcp.py#L376 and https://github.com/flan/staticdhcpd/blob/2.0.x/staticDHCPd/staticdhcpdlib/dhcp.py#L825 can be stripped down to get a minimal implementation of what you want. Basically just delete everything that doesn't look relevant and make the interesting handlers log to your database instead of sending a response.
