### ISSUE TITLE
staticDHCPd version 2.0.0-rc1 doesn't start

### ISSUE THREAD

**Issue by Uzzi** [flan/staticdhcpd#82]
Hi, This is error in log:
`Traceback (most recent call last):
  File "/usr/local/bin/staticDHCPd", line 294, in <module>
    _initialiseDHCP()
  File "/usr/local/bin/staticDHCPd", line 219, in _initialiseDHCP
    database = staticdhcpdlib.databases.get_database()
  File "/usr/local/lib/python2.7/dist-packages/staticdhcpdlib/databases/__init__.py", line 58, in get_database
    return MySQL()
  File "/usr/local/lib/python2.7/dist-packages/staticdhcpdlib/databases/_sql.py", line 174, in __init__
    _PoolingBroker.__init__(self, config.MYSQL_MAXIMUM_CONNECTIONS)
  File "/usr/local/lib/python2.7/dist-packages/staticdhcpdlib/databases/_sql.py", line 133, in __init__
    **self._connection_details
TypeError: type object argument after ** must be a mapping, not NoneType
`
How Can I fix it?
Thanks

**Comment by chusov** [comment]
Deleting the library helped me eventlet 
`pip remove eventlet` or system package python-eventlet

**Comment by flan** [comment]
Wow, sorry, I didn't get a notification for this report. And it's from August. Yikes.

If removing eventlet fixed it, then it would have caused the pool to not be established, and a "mapping" is a generic term for what's usually a dictionary.

The problem here is that a `None` is persisting, since that's what I assigned in the class-def, and it's happening because, in all pooled brokers, `self._connection_details` is populated after the pool is established. This looks like a refactoring gone awry.

**Comment by flan** [comment]
This should now be fixed.

And, if it is, then I should be able to *finally* call this a real release, since @chusov appears to have validated that Oracle works... just in time for the death of Python 2 and need for me to hurry up and start the official Python 3 port.
