### ISSUE TITLE
DHCPRENEW support

### ISSUE THREAD

**Issue by andrew-azarov** [flan/staticdhcpd#91]
Would be great to get DHCPRENEW support to drop old assignments.

**Comment by flan** [comment]
This isn't possible with how the reference dynamism module works, since it just uses a primitive in-memory map of a network and some naive probing to maintain post-restart continuity.

The recently committed (to be tested in the next week or two) Redis-backed dynamic-allocation module should be more robust, since it can make use of NAK with multiple servers and authoritatively track 1:1 associations with persistence.

I'm also not entirely sure I understand your concern or use-case, so I'm just assuming you've enabled the reference dynamism module and that this is the relevant context.
